---
title: "Inspection of ParlGov Data"
date: "`r format(Sys.time(), '%d %B, %Y')`"
params: 
  authors: "Authors are anonymized"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_float: true
    code_folding: hide
    df_print: paged
---

#### `r params$authors` {-}

# List of tables in the data 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(RSQLite)
library(tidyverse)
library(DBI)
library(dbplyr)
library(lubridate)

con <- dbConnect(RSQLite::SQLite(), dbname = here::here("data","parlgov-development.db"))

con %>% dbListTables()
```

# List of countires in the data set
```{r test}
# Read in the database


positions <- tbl(con, "viewcalc_party_position") %>% collect()


tbl(con, "view_election") %>% collect() %>% pull(country_name) %>% unique()
```

# Elections over time for our countries 

We show the vote_share * the left_right rating of the elected parties.

```{r test2, message=FALSE, warning=FALSE}
tbl(con, "view_election") %>% collect() %>% 
  mutate(election_date = ymd(election_date)) %>% 
  filter(country_name %in% c("Germany", "France", "Poland", "United Kingdom", "Netherlands")) %>% 
  group_by(country_name, election_date) %>% 
  summarise(lr = mean(vote_share * left_right, na.rm = TRUE),
            lr_split = sd(vote_share / 100 * left_right, na.rm = TRUE)) %>% 
  ggplot() +
  aes(x = election_date) +
  aes(y = lr) +
  aes(size = lr_split) +
  aes(colour = lr_split) +
  aes(group = country_name) +
  geom_point() +
  geom_line(alpha = 0.5) +
  scale_y_continuous(limits = c(0, 100), name = "Left Right Position (0 left, 100 right)") +
  scale_x_date(name = "Election Year") +
  scale_color_viridis_c(option = "B", name = "Polarization") +
  scale_size(name = "Polarization") +
  facet_wrap(~country_name)
```

# Elections over time using weighted means

```{r test3, message=FALSE, warning=FALSE}
tbl(con, "view_election") %>% collect() %>% 
  mutate(election_date = ymd(election_date)) %>% 
  filter(country_name %in% c("Germany", "France", "Poland", "United Kingdom", "Netherlands")) %>% 
  group_by(country_name, election_date) %>% 
  summarise(lr = weighted.mean(left_right, vote_share, na.rm = TRUE),
            lr_split = sqrt(Hmisc::wtd.var(left_right, vote_share, na.rm = TRUE))) %>% 
  ggplot() +
  aes(x = election_date) +
  aes(y = lr) +
  aes(size = lr_split) +
  aes(colour = lr_split) +
  aes(group = country_name) +
  geom_point() +
  geom_line(alpha = 0.5) +
  scale_y_continuous(limits = c(0, 10), name = "Left Right Position (0 left, 10 right)") +
  scale_x_date(name = "Election Year") +
  scale_color_viridis_c(option = "B", name = "Polarization") +
  facet_wrap(~country_name)

```



```{r db_disconnect, message=FALSE, warning=FALSE, include=FALSE}

dbDisconnect(con)

```

