---
title: "Contents of the survey"
date: "`r format(Sys.time(), '%d %B, %Y')`"
params: 
  authors: "Authors are anonymized"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_float: true
    code_folding: hide
    df_print: paged
---




# Filterbubble awareness
In the following, the dependent variables. If the uses variables were retrieved directly from the questionnaire data, only the questionnaire question is presented, otherwise, the neccessary calculations are explained as well. The used tests can be found on the results page of this website. 


## Awareness Groups
To test what factors influence the awareness of filter bubbles regarding political opinion formation and whether they differ depending on nationality, the awareness of filter bubbles regarding political opinion formation needs to be measured to be used as the independent variable of this study. This was done by building three awareness groups by considering the level of awareness of filter bubbles to be a combination of the likelihood of being subjected to a filter bubble and knowing what the term means. The three resulting awareness groups are the following:  

* Unaware:  
The participants who were subjected to a filter bubble and not familiar with the term. They are likely to not know that they are trapped in a filter bubble nor that the phenomena exists, which makes them unaware of filter bubbles in general. 
* Implicitly aware:  
The participants who were either subjected to a filter bubble but familiar with the term, or not subjected to a filter bubble but not familiar with the term. Though these participants have some knowledge of the filter bubble, either by knowing the term or by not being subjected to it, their knowledge is not complete. They thus show partially aware behaviour. 
* aware:  
The participants who were not subjected to a filter bubble and familiar with the term. They know that a filter bubble exists and their behaviour shows they are also not subjected to one. Their knowledge of the phenomena might have influenced their behaviour. 


## likelihood of being subjected 

To calculate the likelihood that a participant was subjected to a filter bubble, the questionnaire presented the users with seven mock-up Facebook posts depicting polarizing political statements. The users both indicated to what extent they agreed to the statement ($x_p$) and what proportion of the population they thought would agree to the statement ($x_n$). From this, a measure for how likely a participant was to be subjected to a filterbubble was calculated through several steps:  

* Calculate $|x_p - x_n|$ for each of the seven messages;
* Calculate the mean of the the seven absolute differences ($x_{filter}$). This value indicated the size of the mean opinion differences of the participants and the population of their country;
* For each nationality, the mean of the standard deviations for $x_p$ of the seven messages was calculated. This value indicated how large the opinion differences between the participants for each nationality actually were. The resulting percentage $x_{diff}$ differed for each nationality;
* Finally, a new variable was created to save whether the participant was likely to be subjected to a filter bubble or not. If $x_{filter} < x_{diff}$, the participant was likely to be subjected to a filter bubble. If $x_{filter} \geq x_{diff}$ the participant was not likely to be subjected to a filterbubble. 


## knowing the term 

Whether the participant was familiar with the term filter bubble was tested by including the following question in the questionnaire:  

Do you know what is meant with the term ``filter bubble''?  

* yes
* no


# Demographics (H1)

## gender 

What is your gender?  

* female
* male 

## age 

What is your age? [open (numerical) text question]

## education 

The question regarding education was the following: What is the highest level of education you have completed?

However, the answer options to this multiple choice question differed per nationality since different countries have different educatioinal systems which are not directly comparable. To be able to use education as a variable in this study, a new variable consisting of two levels "high education" and "low education" was computed. For the sake of simplicity, we labeled everything below a university bachelor degree as a low level of education. 


# Personality (H2)


## agreeableness 
* I see myself as someone who is generally trusting.
* I see myself as someone who tends to find fault with others. [recoded]

## conscientiousness 
* I see myself as someone who tends to be lazy. [recoded]
* I see myself as someone who does a thorough job.

## extraversion
* I see myself as someone who is reserved. [recoded]
* I see myself as someone who is outgoing, sociable. 

## neurotism 
* I see myself as someone who is relaxed, handles stress well. [recoded]
* I see myself as someone who gets nervous easily. 

## openness 
* I see myself as someone who has few artistic interests. [recoded]
* I see myself as someone who has an active imagination. 


# Media Diversity (H3)

## digital diversity
The participants indicated the percentage of digital media they used ($x_{digital}$) compared to conventional media using a slider ranging from 0 to 100\%. When a participant answered 50\%, this meant that he/she uses digital and convential media equally frequent and the diversity would thus be maximal. We therefore used the following method to calculate a measure for the diversity of media use when comparing digital and convential media: $|50-x_{digital}|$. The smaller this value, the more diverse the media use. 

## general diversity
The participants also received a 6-point Likert scale question (0 = seldom or never \& 5 = daily) that asked them to indicate how frequently they use different types of media. From this question we extracted three factors: social media, broadcast media and print media.  

The general media diversity was then calculated by taking the mean of the standard deviations between the different types of media (the factors). A small mean standard deviation indicated a high level of media diversity since the different types of media were then used similarly frequent.  

## total frequency
The mean media frequency from the previously mentioned 6-point Likert scale question (0 = seldom or never \& 5 = daily) was calculated to indicate the average frequency of media use overall. The subquestions were the following:  

* Facebook (explicitly)
* social media in general
* television (also online)
* radio (also online)
* newspapers/magazines (offline)
* newspapers/magazines (online)
* Internet (without social media)

## social frequency
Was the mean of the subquestions:  

* Facebook (explicitly)
* social media in general

## broadcast frequency
Was the mean of the subquestions:  

* television (also online)
* radio (also online)

## print frequency
Was the mean of the subquestions:  

* newspapers/magazines (offline)
* newspapers/magazines (online)
* Internet (without social media)



# Facebook use (H4)

## having an account
Do you use Facebook?  

* yes 
* no

## read only 
6-point Likert scale: 0 = completely disagree \& 5 = completely agree:  

* Actually, I only use Facebook to read posts 

## share 
6-point Likert scale: 0 = completely disagree \& 5 = completely agree:  

* I regularly share posts with a political content on Facebook 

## like
6-point Likert scale: 0 = completely disagree \& 5 = completely agree:  

* I often like posts with a political content on Facebook 

## comment
6-point Likert scale: 0 = completely disagree \& 5 = completely agree:  

* I often comment on posts with a policital content on Facebook

## activeness
Was calculated as the mean of the following questions, since merely reading Facebook posts was not considered to be active Facebook behaviour:  

6-point Likert scale: 0 = completely disagree \& 5 = completely agree:  

* I regularly share posts with a political content on Facebook
* I often like posts with a political content on Facebook
* I often comment on posts with a policital content on Facebook

## friends 
How many Facebook friends do you approximately have?  

* 0 - 50
* 51 - 100
* 101 - 200
* 201 - 300
* 301 - 400
* 401 - 500 
* 500+

## frequency
From the question on the frequency of media use the question on Facebook explicitly was evaluated.  

6-point Likert scale: 0 = seldom or never \& 5 = daily:  

* Facebook (explicitly)



# Political Interest (H5)

## political interest
Political interest was calculated by taking the mean of the following subquestions. The higher the value, the more politically interested a participant was.  

6-point Likert scale: 0 = completely disagree \& 5 = completely agree  

* I am interested in politics
* I try to stay up to date on political events
* To me it is important to use my right to vote
* I have restrained to participate in the elections out of protest before
* I have chosen for another political party out of protest before
* I would be societally or politically active (or already am)
* I am interested in politics on an international level
* I would participate in political protests (or already have)
* I am interested in European politics
* I am a member of a pressure group/political party/organization or an association

## internal political efficacy
Internal political efficacy was calculated by taking the mean of the following subquestions. The higher the value, the higher the level of internal political efficacy was for a participant.  

6-point Likert scale: 0 = completely disagree \& 5 = completely agree  

* I understand important political questions well and I am able to evaluate them
* I dare to actively participate in a conversation on political matters


# Political Opinion (H6)

## estimated
The participants were directly asked to estimate how left- or right-wing their political opinion is using the Left-Right Self-Placement scale by Breyer (2015). This gave us a value between 1 and 10 (1 = left-wing \& 10 = right-wing). From this a percentage was calculated with 0\% being left-wing and 100\% being right wing. 

## calculated
The participants completed the following question with strongly left-wing or right-wing statements. To minimize sequence effect the order of this question was randomized. Some of the questions were recoded so that 0 equaled left-wing and 5 right-wing. Afterwards, the mean was taken and a percentage was calculated with 0\% being left-wing and 100\% being right wing.  

6-point Likert scale: 0 = strongly disagree \% 5 = strongly agree (examplary for Netherlands):  

* A real democracy is only possible when there is no capitalism anymore [recoded]
* Fascist visions have gotten a threatening size in Europe [recoded]
* Socialism is in principle a good idea that has been executed badly [recoded]
* In the Netherlands the gap between the possessing and working class still exists [recoded]
* Only major economic players profit from globalization [recoded]
* The international financial markets have caused inequality to grow worldwide [recoded]
* The interests of the employee should be well represented [recoded]
* Because of the many foreigners, Europe is losing its own identity
* Foreigners who want to stay in the Netherlands should adapt to the Dutch culture 
* We should finally dare to choose for a strong national feeling again
* Dutch interests on an international level should be pushed harder by Dutch politics
* In their history, other nations have at least been equally guilty as the Germans in the Nazi-time [recoded]
* The Netherlands should be protected from the competition of cheap employees from abroad
* At this moment, the Netherlands need one strong political party that represents the entire nation

