# Introduction
As many authors have noted before, the Internet has changed the way in which media is produced and perceived [e.g., @flaxman2016; @trilling2016]. It has made the production of media easier, cheaper, and more dynamic and as a result more media is available. Mechanisms like search engines enable us to easily find the media we are looking for, wherever we are and whatever we are doing, thereby lifting the restriction on the amount of media we are able to acquire. In addition, mainly because of social networking sites, we are no longer merely the consumers of media, but we can be the producers as well. Social networking sites like Facebook and Twitter allow users to like, share, and comment on the media they perceive and thus directly reveal their opinion to their online network.  
For a long time, scholars have been discussing whether these possibilities the Internet provides are a good thing [e.g., @vanalstyne1996; @williams2007]. Politics thereby seems to be a recurring theme [e.g., @garrett2009; @colleoni2014]. Regarding politics, the fear exists that the large amount of available media on the Internet might cause users to mainly consume media that contains the political views they already agree with. When taken to the extreme, users could then become oblivious to other perspectives which could divide the population in several groups supporting different extreme political opinions. In political science this is referred to using terms like polarization, fragmentation, segregation, and even extremism. When this were to happen, this could threaten the existence of healthy democracies [e.g., @hara2015].  
Terms that are often mentioned when discussing these undesirable consequences of the Internet on politics are *echo chambers* and *filter bubbles* [@pariser2011; @sunstein2017]. Echo chambers thereby refer to the chambers citizens lock themselves in when choosing to mainly consume media that contains the political views they support. In these chambers they are surrounded by like-minded others and the lack of contradicting opinions convinces them more of their own [@sunstein2017, 1--12]. Filter bubbles on the other hand are not entered by choice. They are a result of the many filtering algorithms that are active online to help us find the media we like or are looking for. Since these filtering algorithms are often personalized, over the long haul there is a risk of people only seeing media that coincides with their already existing beliefs. As Pariser [-@pariser2011, 9--10] puts it, people then end up in "unique universes of information" in which different people receive different truths. He calls these universes *filter bubbles*.  
Although in the end, both phenomena limit the diversity of the users' received information, thereby possibly having consequences like political polarization, filter bubbles might be more threatening because users are not necessarily aware of the fact that the media they receive is being filtered. Even though many scholars have suggested that users are unaware of the filtering algorithms [e.g., @cozza2016; @zuiderveen2016], only few have actually tested this assumption [e.g., @epstein2015, @eslami2015]. Furthermore, we are not aware of any studies specifically testing what user aspects cause people to be (un)aware of filter bubbles. However, since the awareness of filter bubbles will most likely eliminate the possible political consequences, we believe that it is important to know what user aspects make people (un)aware of filter bubbles. This information can then be used to expand the awareness of filter bubbles and prevent the phenomenon from negatively influencing our democracies. The present work will therefore provide first insights into answering the question: 

> *RQ*: How does user diversity influence the awareness of filter bubbles regarding political opinion formation?  

The research question was addressed using a questionnaire that was distributed in the Netherlands and measured the awareness using two criteria: the likelihood of being subjected to a filter bubble and the familiarity with the term. In the next chapter we will further explain the underlying problems regarding filter bubbles and introduce our hypotheses. We will then move on to part two of the present work in which we will describe the study we conducted and answer the research question based on our findings.  
